<?php

/**
 * @file
 * Main file for the Mortagage Misc module, which containg logics for form and node alter.
 * 
 * @ingroup mortgage_misc
 */


function mortgage_misc_menu() {
  $items['welcome'] = array(
	  'title' => t('Welcome'),
		'description' => 'Welcome Page',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'mortgagespeak_welcome',
		'access arguments' => array('access content'),
  );
  $items['my-page/%'] = array(
	  'title' => t('My Page'),
		'description' => 'My Page',
		'page arguments' => array(1),
		'page callback' => 'mortgagespeak_my_page',
		'access arguments' => array('access content'),
	);

  return $items;
}


function mortgagespeak_my_page(){
	global $user;
	$output = 'comes';
	return $output;
}


function mortgagespeak_welcome(){
	global $user;
	$output = '';
	return $output;
}

function mortgage_misc_form_alter(&$form, &$form_state, $form_id) {

 	if($form_id == 'user_register_form') {
		$form['select_all'] = array(
	    '#type' => 'checkbox',
	    '#title' => t('Select All'),
  	);
 	  $form['actions']['submit']['#value'] = 'Register';
 	}

  if($form_id == 'webform_client_form_42') {
    $form['actions']['submit']['#value'] = 'Submit !';
    $form['submitted']['content_types']['#empty_option'] = 'Content Types';
    $form['submitted']['tag_types']['#empty_option'] = 'Tag Types';
  }
}

function mortgage_misc_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
	global $user;
	$user_topics = '';
	$user_info = user_load($user->uid);
	if($form['#id'] == 'views-exposed-form-tracked-news-page'){
		$user_news = array('All'=>'All Tracked News');
		if(isset($user_info->field_news_topics[LANGUAGE_NONE]) && !empty($user_info->field_news_topics[LANGUAGE_NONE])){
			foreach($user_info->field_news_topics[LANGUAGE_NONE] as $tidKey=>$tidVal){
				$user_topics = taxonomy_term_load($tidVal['tid']);
				$user_news[$tidVal['tid']] = $user_topics->name;
			}   
		}
		$form['field_alpha_news_topics_tid_1']['#options'] = $user_news;
		#$form['field_alpha_news_topics_tid_1']['#value'] = 'All';		
    if(!empty($_REQUEST['field_alpha_news_topics_tid_1']))
        $form['field_alpha_news_topics_tid_1']['#value'] = $_REQUEST['field_alpha_news_topics_tid_1'];  	
  }

	if($form['#id'] == 'views-exposed-form-tracked-companies-page'){    
    $user_company = array('All'=>'Company A-M ');
    $user_company1 = array('All'=>'Company N-Z ');

    $arrATOM = array('1', '3', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm');
    $arrMTOZ = array('n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

    if(isset($user_info->field_company_tags[LANGUAGE_NONE]) && !empty($user_info->field_company_tags[LANGUAGE_NONE])){
        foreach($user_info->field_company_tags[LANGUAGE_NONE] as $tidKey=>$tidVal){
            $user_tags = taxonomy_term_load($tidVal['tid']);
            if(in_array(strtolower($user_tags->name[0]), $arrATOM)) {
                $user_company[$tidVal['tid']] = $user_tags->name;
            }
            else if(in_array($user_tags->name[0], $arrMTOZ)) {
                $user_company1[$tidVal['tid']] = $user_tags->name;
            }
        }
    }
    $form['company_tag']['#options'] = $user_company;    
    if(!empty($_REQUEST['company_tag'])) {
      $form['company_tag']['#value'] = $_REQUEST['company_tag'];
    }
    else{
    	$form['company_tag']['#value'] = 'All';
    }

    $form['company_tag1']['#options'] = $user_company1;
    if(!empty($_REQUEST['company_tag1'])){
    	$form['company_tag1']['#value'] = $_REQUEST['company_tag1'];
    }
    else{
    	$form['company_tag1']['#value'] = 'All';
    }
        
 }
  
}

function mortgage_misc_entity_info_alter(&$entity_info) {
  $entity_info['taxonomy_term']['uri callback'] = 'mortgage_misc_taxonomy_term_uri';
}

function mortgage_misc_taxonomy_term_uri($term) {
  global $user;
  global $base_url;
  $user_info = user_load($user->uid);

  if(in_array('News Intelligence', $user->roles)) {
    $arrATOM = array('1', '3', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm');
    $arrMTOZ = array('n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
    $user_company = array();
    
    if(isset($user_info->field_company_tags) && !empty($user_info->field_company_tags)) {
      foreach ($user_info->field_company_tags[LANGUAGE_NONE] as $keyComp => $valueComp) {
        $user_company[$valueComp['tid']] = $valueComp['tid'];
      }
    }
    switch ($term->vocabulary_machine_name) { 
      case 'company_tags':
        $parents = taxonomy_get_parents($term->tid);
        if(!empty($user_company)) {
          foreach ($user_company as $key => $value) {
            if(in_array($term->tid, $user_company)) {
              $comp = taxonomy_term_load($term->tid);
              if(in_array(strtolower($comp->name[0]), $arrATOM)) {
                  $user_comp[$term->tid] = $comp->name;
                  $company_url = $base_url . '/my-page/tracked-companies?company_tag='. $term->tid .'&company_tag1=All';
              }
              else if(in_array($comp->name[0], $arrMTOZ)) {
                  $user_comp1[$term->tid] = $comp->name;
                  $company_url = $base_url . '/my-page/tracked-companies?company_tag=All&company_tag1='. $term->tid;
              }
            }
            else {
              $company_url = $base_url . '/my-page/tracked-companies';
            }
          }
        }
        else {
          $company_url = $base_url . '/my-page/tracked-companies';
        }
        return array(
            'path' => $company_url,
        );
      break;
    }
  }
  // default taxonomy term uri
  return taxonomy_term_uri($term);
}