<?php

/**
 * @file
 * Main file for the Mortagage Misc module, which containg logics for form and node alter.
 * 
 * @ingroup mortgage_misc
 */


function mortgage_misc_menu() {
  $items['welcome'] = array(
	  'title' => t('Welcome'),
		'description' => 'Welcome Page',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'mortgagespeak_welcome',
		'access arguments' => array('access content'),
  );

  return $items;
}


function mortgagespeak_welcome(){
	global $user;
	$output = '';
	return $output;
}

function mortgage_misc_form_alter(&$form, &$form_state, $form_id) {
 	if($form_id == 'user_register_form'){
 		$form['actions']['submit']['#value'] = 'Register';
 	}
}