<?php


/**
 * @file
 * Main file for the Mortagage Newsletter module, which containg logics for generating newsletter according to selected user's data.
 * 
 * @ingroup mortgage_newsletter
 */


/*
  implements hook_menu() to create handle newletter hook
*/
function mortgage_newsletter_menu() {
  $items['create-newsletter'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Select User List Form', //page title
    'description' => 'A form to select list of users to generate newsletter.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('select_user_list_form'), //put the name of the form here
    'access arguments' => array('administer users')
  );
 
  $items['create-weekly-newsletter'] = array(
  'type' => MENU_CALLBACK,
  'title' => 'Select User List Form', //page title
  'description' => 'A form to select list of users to generate newsletter.',
  'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
  'page arguments' => array('select_user_list_form'), //put the name of the form here
  'access arguments' => array('administer users')
  );
  
  $items['adduser'] = array(
    'title' => 'Newletter Edit Form',
    'page callback' => 'newsletter_edit_forms',
    'access callback' => TRUE,
  );
  return $items;
}


/* 
    This function is used to select users list for newsletter
*/
function select_user_list_form($form, &$form_state) {
  drupal_set_title(t("Newsletter Form"));

  $query = db_select('users', 'u');
  $query->fields('u', array('uid', 'name'));
  $query->condition('u.status', '1', '=');
  $query->orderBy('name', 'ASC');
  $result = $query->execute(); 
  while ($record = $result->fetchAssoc()) {
    $uid[$record['uid']] = $record['name'];
  }  

  $multiple = 20;
  $default_newsletter = "cn";

  $options = array(
    'cn' => t('Client Newsletter'),
    'pn' => t('Public Newsletter'),
  );

  $form['newsletter_type'] = array(
    '#type' => 'radios',
    '#title' => t('Newsletter Type'),
    '#options' => $options,
    '#default_value' => $default_newsletter,
  );

  $form['select_user'] = array(
    '#type' => 'select',
    '#title' => t('Select User'),
    '#options' => $uid,
    '#multiple' => $multiple, 
    #'#size' => $multiple ? min(12, count($uid)) : 0,
    '#size' => 0,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}


function newsletter_edit_forms() {
  $content ="";
  $content .= render(drupal_get_form('newsletter_add_usercustom_form'));
  // $content .= render(drupal_get_form('newsletter_remove_usercustom_form'));
  $content .= render(drupal_get_form('subscription_list_form'));
  return $content;
}

function select_user_list_form_validate($form, &$form_state) {
  if($form_state['values']['newsletter_type'] == 'cn') {
    if (empty($form_state['values']['select_user'])) {
     form_set_error('user', t('select user from dropdown.'));
    }
  }
}

function select_user_list_form_submit($form, &$form_state) {
  global $base_url;

  $debug = FALSE;
  $body = '';
  $pass = '';
  $user_pass = '';
  $category_name = '';
  $arr_newstopics = array();
  $arr_companytags = array();
  $arr_tabplacements = array();

  $abbrtimezone = "CST";
  date_default_timezone_set(timezone_name_from_abbr($abbrtimezone));
  $today              = strtotime("00:00:01");
  $yesterday          = strtotime("-1 day", $today);
  $current            = strtotime("now");
  
  $arr_newslist = array();
  $url_pressrelease = 'http://' . $_SERVER['HTTP_HOST'];

  if($form_state['values']['newsletter_type'] == 'cn') {
    foreach ($form_state['values']['select_user'] as $key => $vals) {    
          $userid = $vals;
          $user = user_load($userid);
          if(!empty($user->field_newsletter_password)){
            $user_pass = $user->field_newsletter_password['und'][0]['value'];
          }
          else{
            $user_pass = "";
          }

          if ($debug) {
            print("<pre> :: User ::");
            print_r($user);
            print("</pre>");
          }

          switch ($user->name) {
            case "FAF":
              $user->name = "#FAF#";
              $pass = "#FAF@1234#";
              break;
            default:
              $user->name = $user->name;
              $pass = $user_pass;
            
          }


          #################################################################
          # Fetch Selected Company Tags related content section start....
          #################################################################

          $arr_user_company_tags = array();
          if (!empty($user->field_company_tags)) {
            foreach ($user->field_company_tags['und'] as $key => $val) {
              $arr_user_company_tags[] = $val['tid'];
            }
          }

          $query = db_select('node', 'n');
          $query->leftJoin('field_data_field_company_tag', 'fct', 'fct.entity_id = n.nid');
          $query->fields('n', array('nid'));
          $query->condition('n.status', '1', '=');
          $query->condition('n.type', 'alpha_content', '=');

          if ($form_state['complete form']['#action'] == '/create-weekly-newsletter') {
            $yesterday  = strtotime("-7 day", $current);
            $query->condition('n.created', array($yesterday, $current), 'BETWEEN');
          }
          else {
            if ($form_state['complete form']['#action'] == '/create-newsletter') {
              $query->condition('n.created', array($today, $current), 'BETWEEN');
            }
          }
          

          if (!empty($arr_user_company_tags))
            $query->condition('fct.field_company_tag_tid', $arr_user_company_tags, 'IN');

          $query->orderBy('n.created', 'DESC');    
          $result = $query->execute();

          $arr_user_company_tags_nids = array();
          if ($result->rowCount() != 0 && (!empty($arr_user_company_tags))) {
            $i = 1;        
            while ($record = $result->fetchAssoc()) {
              if (!array_key_exists($record['nid'], $arr_newslist)) {
                $arr_newslist[$record['nid']] = $record['nid'];
                $arr_companytags[$record['nid']] = $record['nid'];
              }
              $arr_user_company_tags_nids[$record['nid']] = $record['nid'];
            }    
          } 
       

          #################################################################
          # Fetch Selected Company Tags related content section end....
          #################################################################


          #################################################################
          # Fetch Selected Newstopics related content section start....
          #################################################################
          $arr_user_news_topics = array();
          if (!empty($user->field_news_topics)) {
            foreach ($user->field_news_topics['und'] as $key => $val) {
              $arr_user_news_topics[] = $val['tid'];
            }
          }   

          $query = db_select('node', 'n');
          $query->leftJoin('field_data_field_alpha_news_topics', 'fnt', 'fnt.entity_id = n.nid');
          $query->leftjoin('field_data_field_tab_placement', 'fct', 'fct.entity_id = n.nid');
          $query->condition('fct.field_tab_placement_tid', '701', '=');
          $query->fields('n', array('nid'));
          $query->condition('n.type', 'alpha_content', '=');
          $query->condition('n.status', '1', '=');
          if ($form_state['complete form']['#action'] == '/create-weekly-newsletter') {
            $yesterday  = strtotime("-7 day", $current);
            $query->condition('n.created', array($yesterday, $current), 'BETWEEN');
          }
          else {
            if ($form_state['complete form']['#action'] == '/create-newsletter') {
              $query->condition('n.created', array($today, $current), 'BETWEEN');
            }
          }

          if (!empty($arr_user_news_topics))
            $query->condition('fnt.field_alpha_news_topics_tid', $arr_user_news_topics, 'IN');

          $query->orderBy('n.created', 'DESC');    
          $result = $query->execute();

          $arr_user_news_topics_nids = array();
          if ($result->rowCount() != 0 && (!empty($arr_user_news_topics))) {
            $i = 1;        
            while ($record = $result->fetchAssoc()) {
              if (!array_key_exists($record['nid'], $arr_newslist)) {
                  $arr_newslist[$record['nid']] = $record['nid'];
                  $arr_newstopics[$record['nid']] = $record['nid'];
                }
              $arr_user_news_topics_nids[$record['nid']] = $record['nid'];
            }    
          }
          #################################################################
          # Fetch Selected Newstopics related content section end....
          #################################################################


          #######################################################################
          # Fetch Selected Perspective & Press Release content section start....
          ########################################################################    

          $tab_placement = array('705', '706');
          $query = db_select('node', 'n');    
          $query->fields('n', array('nid'));
          $query->join('field_data_field_tab_placement', 'fct', 'fct.entity_id = n.nid');
          $query->condition('n.type', 'alpha_content', '=');
          $query->condition('n.status', '1', '=');
          $query->condition('fct.field_tab_placement_tid', $tab_placement, 'IN');
          if ($form_state['complete form']['#action'] == '/create-weekly-newsletter') {
            $yesterday  = strtotime("-7 day", $current);
            $query->condition('n.created', array($yesterday, $current), 'BETWEEN');
          }
          else {
            if ($form_state['complete form']['#action'] == '/create-newsletter') {
              $query->condition('n.created', array($today, $current), 'BETWEEN');
            }
          }

          $query->orderBy('n.created', 'DESC');    
          $result = $query->execute();

          $arr_perspective_content = array();
          if ($result->rowCount() != 0) {
            $i = 1;        
            while ($record = $result->fetchAssoc()) {
              if (!array_key_exists($record['nid'], $arr_newslist)) {
                //if(!array_key_exists($record['nid'], $arr_companytags)) {
                  $arr_newslist[$record['nid']] = $record['nid'];
                  $arr_tabplacements[$record['nid']] = $record['nid'];
              }
              //}
              $arr_perspective_content[$record['nid']] = $record['nid'];
            }    
          }    

         /*    $query = db_select('node', 'n');
          $query->join('field_data_field_assign_customas', 'fac', 'fac.entity_id = n.nid');
          $query->fields('n', array('nid'));
          $query->condition('n.type', 'alpha_content', '=');
          $query->condition('n.created', array($today, $current), 'BETWEEN');

          $query->orderBy('n.created', 'DESC');    
          $result = $query->execute();

          $arr_press_releases = array();
          if($result->rowCount() != 0){
            $i = 1;        
            while ($record = $result->fetchAssoc()) {
              if(!array_key_exists($record['nid'], $arr_newslist)) {
                $arr_newslist[$record['nid']] = $record['nid'];
              }
              $arr_press_releases[$record['nid']] = $record['nid'];
            }    
          }*/        
          #################################################################
          # Fetch Selected Perspective & Press Release content section start....
          #################################################################*/

          // Fetch linked Recommendations count

          $qry_linkin = db_query("SELECT count(node.nid) AS nid
          FROM 
          node node
          INNER JOIN field_data_field_recommended_for_linkedin field_data_field_recommended_for_linkedin ON node.nid = field_data_field_recommended_for_linkedin.entity_id AND (field_data_field_recommended_for_linkedin.entity_type = 'node' AND field_data_field_recommended_for_linkedin.deleted = '0')
          WHERE node.status = '1' AND node.type = 'alpha_content' AND field_data_field_recommended_for_linkedin.field_recommended_for_linkedin_value = '1'");
          $res_linkin = $qry_linkin->fetchAssoc();
          $linkedin_cnt = $res_linkin['nid'];

          #################################################################
          # Debug Variables section start....
          #################################################################
          if ($debug) {

            print("<pre> :: arr_user_news_topics ::");
            print_r($arr_user_news_topics);
            print("</pre>"); 

            print("<pre> :: arr_user_company_tags ::");
            print_r($arr_user_company_tags);
            print("</pre>");

            print("<pre> :: arr_user_company_tags ::");
            print_r($arr_user_company_tags);
            print("</pre>");

            print("<pre> :: arr_user_news_topics ::");
            print_r($arr_user_news_topics);
            print("</pre>"); 

            print("<pre> :: arr_user_company_tags_nids ::");
            print_r($arr_user_company_tags_nids);
            print("</pre>");

            print("<pre> :: arr_user_news_topics_nids ::");
            print_r($arr_user_news_topics_nids);
            print("</pre>");

            print("<pre> :: arr_perspective_content ::");
            print_r($arr_perspective_content);
            print("</pre>");

            print('<pre :: arr_tabplacements style="color:red;">');
            print_r($arr_tabplacements);
            print('</pre>');

            print("<pre> :: arr_press_releases ::");
            print_r($arr_press_releases);
            print("</pre>");

            print("<pre> :: arr_newslist (FOR UNIQUE NODES ONLY) ::");
            print_r($arr_newslist);
            print("</pre>");
          }
          #################################################################
          # Debug Variables section end....
          #################################################################


          #################################################################
          # Create Newsletter Node/Content section start....
          #################################################################
          $node = new StdClass();
          $node->type = 'simplenews';
          $node->status = 1;
          $node->uid = 1;
          $node->language = LANGUAGE_NONE;

          if ($form_state['complete form']['#action'] == '/create-weekly-newsletter') {
            $node->title = "Weekly Newsletter";
          } 
          else {
            if ($form_state['complete form']['#action'] == '/create-newsletter') {
             $node->title = "Newsletter";
            }
          }
          $node->body['und'][0]['format'] = 'full_html';

          $primg = $base_url . '/sites/default/files/pr.png';
          $tracked_topicimg = $base_url . '/sites/default/files/track_news.png'; 
          $linkcheck_mark = $base_url . '/sites/default/files/linked-in-check.png';
          //$tracked_topicimg = $base_url . '/sites/default/files/Key.png'; 

          # Template Main Section Start...
          $body .= '<table align="center" class="main-outer-table" style="width: 100%; max-width: 800px; margin-top: 50px; border-spacing:0; border-collapse: collapse; border: none;">
            <tbody>';

              # Template Header Section Start...
              $body .= '<tr class="header-section" style="background: #2e8cf0;">
                          <td style="padding: 0; margin: 0; border: 1px solid #2e8cf0; line-height: normal; ">
                          <table cellpadding="10" style="width: 100%; margin: 5px auto; border-spacing:0; border-collapse: collapse; padding: 0; background-color: #2e8cf0; border: 1px solid #2e8cf0; ">
                            <tbody>
                              <tr>
                                <td style="padding: 0 40px; margin:0; line-height: normal; ">
                                <table align="center" class="header-table" style="margin: 0px auto; width: 100%; border-collapse: collapse; padding: 0; border: none; line-height: normal; ">
                                  <tbody>
                                    <tr>
                                      <td style="padding: 7px 0; margin:0; line-height: normal; " width="55"><a href="http://mortgagespeak.com" style="text-decoration: none;"><img alt="" src="'. $base_url .'/sites/default/files/ms.png" style="vertical-align: middle;" /></a></td>
                                      <td style="padding: 7px 0 0; margin: 0; vertical-align: top;">
                                      <table style="padding: 0; margin: 0; border-spacing: 0; border-collapse: collapse; width: 100%; border: none;">
                                        <tbody>
                                          <tr>
                                            <td style="padding: 0; margin: 0; letter-spacing: 1px; font-family: arial; color: #ffffff; font-size: 14pt; font-weight: bold;"><span>News Intelligence</span></td>
                                          </tr>
                                          <tr>
                                            <td style="padding: 7px 0 0; vertical-align: bottom; margin: 0; line-height: normal; letter-spacing: 1px; font-family: arial; font-size: 10pt; color: #ffffff;">The news that matters most.</td>
                                          </tr>
                                        </tbody>
                                      </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                          </td>
                        </tr>';
              # Template Header Section End...

              # Template Body Section Start
              $body .= '  <tr class="body-section" style="background: #F4F4F4;">
                            <td style="padding: 0; border: 1px solid #bebfb9; ">
                              <table align="center" class="main-table" style="width: 100%; margin: 0px auto; border-collapse: collapse; padding: 5px; border: none; background-color: #f4f4f4; border: none; ">
                                <tbody>';

                  # Template Sub Header Section Start...

                  $body .= '<tr>
                              <td style="border: 0px none; border-collapse: collapse; border-spacing: 0px; padding: 0 40px;">&nbsp;</td>
                            </tr>
                            <tr>
                              <td style="border: 0px none; border-collapse: collapse; border-spacing: 0px; padding: 0px 5px;">
                                <table style="border-radius: 5px 5px 0 0; padding: 0; border-spacing: 0; border-collapse: collapse; background-color: #ffffff; border: none; margin: 0 auto; width: 100%;" align="center">
                                  <tbody>
                                    <tr>
                                      <td style="padding: 0 20px;">
                                        <div style="width: 100%; border-top: 2px solid #ffffff;">&nbsp;</div>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td style="padding: 0 20px 15px 20px;">
                                        <table style="width: 100%; font-size: 13px; color: #666666; border: 0px solid #fff; border-collapse: collapse; border-spacing: 0; box-sizing: border-box; border-style: none; margin: 0;">
                                          <tbody>
                                            <tr>
                                              <td style="padding: 7px 3px; text-indent: 0px; font-family: arial; background-color: #fefce5;"><span style="font-size: small; font-family: arial, helvetica, sans-serif;"><strong style="font-family: arial;">Headlines</strong></span></td>
                                              <td style="background-color: #fefce5; text-align: center;"><span style="font-size: small; font-family: arial, helvetica, sans-serif;"><strong style="font-family: arial;">Today</strong></span></td>
                                              <td style="background-color: #fefce5; text-align: center;"><span style="font-size: small; font-family: arial, helvetica, sans-serif;"><strong style="font-family: arial;">YTD</strong></span></td>
                                            </tr>
                                            <tr style="background-image: url(\'initial\'); background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
                                              <td style="padding: 7px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333; font-weight: bold;">Linked<span style="color: #0077b5  ">IN</span> Recommendations</span></td>
                                              <td style="padding: 7px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">2</span></td>
                                              <td style="padding: 7px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">25</span></td>
                                            </tr>
                                            <tr>
                                              <td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">Tracked Companies</span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">2</span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">25</span></td>
                                            </tr>
                                            <tr>
                                              <td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">Tracked Sectors</span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">2</span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;">25</span></td>
                                            </tr>
                                            <tr>
                                              <td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #333333;"><strong>Total</strong></span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="color: #333333;"><strong><span style="font-size: small; font-family: arial, helvetica, sans-serif;">2</span></strong></span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;"><span style="color: #333333;"><strong><span style="font-size: small; font-family: arial, helvetica, sans-serif;">25</span></strong></span></td>
                                            </tr>
                                            <tr>
                                              <td style="padding: 5px 3px; text-indent: 0px; font-family: arial;">&nbsp;</td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
                                            </tr>
                                            <tr>
                                              <td style="padding: 7px 3px; text-indent: 0px; font-family: arial; background-color: #edfcf2;"><span style="font-family: arial, helvetica, sans-serif; font-size: small;"><strong>Login</strong></span></td>
                                              <td style="background-color: #edfcf2;">&nbsp;</td>
                                              <td style="background-color: #edfcf2;">&nbsp;</td>
                                            </tr>
                                            <tr>
                                              <td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="color: #126edc;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="' . $base_url . '/user"><span style="font-size: small; font-family: arial, helvetica, sans-serif; color: #126edc;"><span style="color: #2e8cf0;"><span style="color: #126edc;">Your custom news page:</span></span></span></a></span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
                                            </tr>
                                            <tr>
                                              <td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif;"><span style="color: #888888;">un:</span> &nbsp;' . $user->name . '</span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
                                            </tr>
                                            <tr>
                                              <td style="padding: 5px 3px; text-indent: 0px; font-family: arial;"><span style="font-size: small; font-family: arial, helvetica, sans-serif;"><span style="color: #888888;">pw:</span> &nbsp;' . $pass . '</span></td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
                                              <td style="padding: 5px 3px; text-align: center; font-family: arial;">&nbsp;</td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>'; 
                  # Template Sub Header Section End... 

                  # Outer Template Body Section Username & Password Start...

                  $body .= '<tr>
                              <td style="border-spacing: 0px; border-collapse: collapse; width: 100%; padding: 0px 5px;">
                                <table align="center" style="border-radius: 0 0 5px 5px; padding: 0; border-spacing: 0; border-collapse: collapse; background-color: #fff; border: none; margin: 0 auto; width: 100%;">
                                  <tbody>';
                                    /* # Template Body Section Start...
                                    $body .= '<tr class="tr-lvl-3" style="width:100%; ">
                                                <td style="width:100%; background-color: #fff; padding: 5px 20px 15px;border-radius:0 0 5px 5px">
                                                  <table class="tbl-lvl-4" style="border:none;border-spacing:0; border-collapse:collapse;  width:100%;  border-radius:10px">
                                                    <tbody style="width:100%; ">';*/

                                    # Template Body Section Username & Password Start...
                                    $body .= '<tr class="News-intelligence" style="width: 100%;">
                                                <td style="font-family: arial; font-size: 13px; padding: 10px 20px 0 20px; width: 100%; line-height: normal;">
                                                  <table style="width: 100%; font-size: 13px; color: #666666; border: 0px solid #fff; border-collapse: collapse; border-spacing: 0; box-sizing: border-box; border-style: none; margin: 0; border-color: #ffffff; border-width: 0px;" border="0" cellpadding="10" align="center">
                                                    <tbody>
                                                      <tr>
                                                        <td style="padding: 7px; color: #000000; background-color: #0077b5; border-color: #0077b5; border-style: solid; border-width: 1px;">
                                                          <p style="text-align: center;"><span style="color: #ffffff; font-family: arial, helvetica, sans-serif; font-size: small;"><strong>Grow </strong>your brand. Look like a <strong>genius</strong>.<br /></span></p>
                                                        </td>
                                                      </tr>
                                                      <tr>
                                                        <td style="padding: 7px; color: #000000; background-color: #ffffff; border-color: #0077b5; border-style: solid; border-width: 1px;">
                                                          <p style="text-align: center;"><span style="color: #126edc; font-size: medium;"><span style="color: #126edc; text-decoration: none; font-family: arial, helvetica, sans-serif;"><strong><span style="font-size: large; color: #0000ff;">'. $linkedin_cnt .'</span> <span style="color: #333333;">Linked</span><span style="color: #0077b5;">IN</span></strong> <span style="color: #333333;">recommendations</span></span></span></p>
                                                          <p style="text-align: center;"><a style="color: #0000ff; font-size: 13px; text-decoration: none; font-family: arial;" href="' . $base_url .'/linkedin-recommendations" target="_blank"><span style="color: #126edc;"><span style="color: #126edc; font-family: arial, helvetica, sans-serif; font-size: small;">Click Here For All Headlines!</span></span></a></p>
                                                        </td>
                                                      </tr>
                                                    </tbody>
                                                  </table>
                                                </td>
                                              </tr>
                                              <tr class="News-intelligence" style="width: 100%;">
                                                <td style="font-family: arial; font-size: 13px; padding: 10px 20px 0 20px; width: 100%; line-height: normal;">&nbsp;</td>
                                              </tr>
                                              <tr>
                                                <td style="width: 100%; padding: 10px 20px;">
                                                  <p><span style="font-family: arial, helvetica, sans-serif; font-size: x-large; color: #ff6600;"><span style="font-size: x-small;"><span style="color: #808080;"><span style="color: #ff6600; font-size: x-large;">Headlines</span></span></span></span></p>
                                                  <p><span style="font-family: arial, helvetica, sans-serif; font-size: xx-small; color: #ff6600;"><span style="color: #808080; font-size: x-small;">More:</span>&nbsp;&nbsp;&nbsp;<span style="font-size: small;"><a style="color: #0000ff; font-size: 13px; text-decoration: none; font-family: arial;" href="' . $base_url . '/news" target="_blank"><span style="color: #2e8cf0;">News</span></a>&nbsp;&nbsp;<span style="color: #808080;">|</span>&nbsp;&nbsp;<a style="color: #0000ff; font-size: 13px; text-decoration: none; font-family: arial;" href="' . $base_url . '/press-releases" target="_blank"><span style="color: #2e8cf0;">Press Releases</span></a></span></span></p>
                                                </td>
                                              </tr>';
                                    # Template Body Section Username & Password End...

                                    # Template Body Section For All Content Type Start...                    
                                   /* $body .= '<tr>
                                              <td style="padding: 0 20px 20px 20px; width: 100%;">
                                                <table class="both_table" style=" margin: 0px auto; border-collapse: collapse; border: none;">
                                                  <tbody>';*/
                                          if (!empty($arr_newslist)) {
                                           $body .= '<tr>
                                                        <td style="width: 100%;padding: 10px 20px;">
                                                          <table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
                                                            <tbody>';
                                                              foreach ($arr_newslist as $node_id => $value) {
                                                                $topics_name = '';
                                                                $category_name = '';
                                                                $linkedin_recommendations = '';
                                                                $share_linked = '';
                                                                $share_twitter = '';
                                                                $share_fb = '';
                                                                $share_google = '';
                                                                $nodetitle = '';
                                                                $nodedata = '';
                                                                $nodeloads = node_load($node_id);
                                                                $linkedin_recommendations = '';

                                                                $strtitle =  $nodeloads->title;
                                                                $strtitle = str_replace("\"", "'", $strtitle);

                                                                // google short url
                                                                $social_url = $url_pressrelease . '/' . drupal_get_path_alias('node/' . $nodeloads->nid);
                                                                $longurl = array('linked'=>'http://www.linkedin.com/shareArticle?mini=true&url='.$social_url. '&summary='. $strtitle,'twitter'=>'https://twitter.com/intent/tweet?&text='. $strtitle .'&url='. $social_url, 'google' => 'https://plus.google.com/share?url='. $social_url .'&body='. $strtitle, 'fb'=>'http://www.facebook.com/sharer.php?u='. $social_url .'&t='. $strtitle);

                                                                $getshorturl = googleGenerateShortURL($longurl);
                                                                 
                                                                foreach($getshorturl as $key => $shrturl) {
                                                                  $share_linked = $getshorturl['linked'];
                                                                  $share_twitter = $getshorturl['twitter'];
                                                                  $share_google = $getshorturl['google'];
                                                                  $share_fb = $getshorturl['fb'];
                                                                }

                                                                // Link Recommendations image
                                                                if(isset($nodeloads->field_recommended_for_linkedin) && !empty($nodeloads->field_recommended_for_linkedin)) {
                                                                  if($nodeloads->field_recommended_for_linkedin[LANGUAGE_NONE][0]['value'] == 1) {
                                                                    $linkedin_recommendations =  '<tr>
                                                                        <td style="padding: 7px 0 4px 0; vertical-align:middle;"><a href="'. $share_linked .'" style="display:inline-block;" target="_blank"><img src="' . $linkcheck_mark . '" alt="linkedin"/></a></td>
                                                                      </tr>';
                                                                    //$linkedin_recommendations = '<img src="' . $linkcheck_mark . '" alt="linkedin"/>';
                                                                  }
                                                                  else {
                                                                    $linkedin_recommendations = '';
                                                                  }
                                                                }

                                                                if (!empty($nodeloads->field_url)) {
                                                                  $urlalias = $nodeloads->field_url[LANGUAGE_NONE][0]['value'];
                                                                }
                                                                else {
                                                                  $urlalias = $url_pressrelease . '/' . drupal_get_path_alias('node/' . $nodeloads->nid);
                                                                }

                                                                if (!empty($nodeloads->title)) {
                                                                  $data_title = strip_tags($nodeloads->title);
                                                                  $nodetitle = truncate_utf8($data_title, 120, FALSE, TRUE, 1);
                                                                }

                                                                if (!empty($nodeloads->body)) {
                                                                  $datanode = strip_tags($nodeloads->body['und'][0]['value']);
                                                                  $nodedata = truncate_utf8($datanode, 150, FALSE, TRUE, 1); 
                                                                }

                                                                $company_image = '';
                                                                if (in_array($node_id, $arr_companytags)) {
                                                                  if (isset($nodeloads->field_company_tag[LANGUAGE_NONE]) && !empty($nodeloads->field_company_tag[LANGUAGE_NONE])) {
                                                                    $company_tid = $nodeloads->field_company_tag[LANGUAGE_NONE][0]['tid'];
                                                                    $taxo_info = taxonomy_term_load($company_tid);
                                                                    if (isset($taxo_info->field_large_logo) && !empty($taxo_info->field_large_logo)) {
                                                                      $img_url = $taxo_info->field_large_logo['und'][0]['uri'];
                                                                      
                                                                      $company_image = urldecode(file_create_url($img_url));
                                                                    }
                                                                    $category_name = 'Tracked Company';
                                                                  }
                                                                }
                                                                elseif (in_array($node_id, $arr_newstopics)) {
                                                                  if (isset($nodeloads->field_tab_placement[LANGUAGE_NONE]) && !empty($nodeloads->field_tab_placement[LANGUAGE_NONE])) {
                                                                    $topics_name = '';
                                                                    foreach ($nodeloads->field_tab_placement[LANGUAGE_NONE] as $tabkey => $tabvalue) {
                                                                      // News Topics
                                                                      if ($tabvalue['tid'] == '701') {
                                                                        if (isset($nodeloads->field_alpha_news_topics[LANGUAGE_NONE]) && !empty($nodeloads->field_alpha_news_topics[LANGUAGE_NONE])) {
                                                                          foreach ($nodeloads->field_alpha_news_topics[LANGUAGE_NONE] as $topicskey => $topicvalue) {
                                                                            $taxomony = taxonomy_term_load($topicvalue['tid']);
                                                                            $topics_name .= $taxomony->name . ', ';
                                                                          }
                                                                          $topics_name = rtrim($topics_name, ", ");
                                                                        }
                                                                        $category_name = $topics_name;
                                                                        $company_image = $tracked_topicimg;
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                                elseif (in_array($node_id, $arr_tabplacements)) {
                                                                  if (isset($nodeloads->field_tab_placement[LANGUAGE_NONE]) && !empty($nodeloads->field_tab_placement[LANGUAGE_NONE])) {
                                                                    foreach ($nodeloads->field_tab_placement[LANGUAGE_NONE] as $tabkey => $tabvalue) {
                                                                      $category_name = '';
                                                                      
                                                                      // Press Releases
                                                                      if (($tabvalue['tid'] == '705')) {
                                                                        $category_name = 'Press Release';
                                                                        break;
                                                                      }

                                                                      //Prespectives
                                                                      if (($tabvalue['tid'] == '706')) {
                                                                        $category_name = 'Perspectives';
                                                                        break;
                                                                      }

                                                                      //Blogs
                                                                      if (($tabvalue['tid'] == '703')) {
                                                                        $category_name = 'Blogs';
                                                                        break;
                                                                      }
                                                                    }
                                                                    $company_image = $primg;
                                                                  }
                                                                }
                                                                else {
                                                                  if (isset($nodeloads->field_alpha_news_topics[LANGUAGE_NONE]) && !empty($nodeloads->field_alpha_news_topics[LANGUAGE_NONE])) {
                                                                      $topics_name = '';
                                                                      foreach ($nodeloads->field_alpha_news_topics[LANGUAGE_NONE] as $topicskey => $topicvalue) {
                                                                        $taxomony = taxonomy_term_load($topicvalue['tid']);
                                                                        $topics_name .= $taxomony->name . ', ';
                                                                      }
                                                                      $topics_name = rtrim($topics_name, ", ");
                                                                  }
                                                                  $category_name = $topics_name;
                                                                  $company_image = $tracked_topicimg;
                                                                }
                                                                $url = $urlalias;
                                                                $body .= '<tr>
                                                                            <td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;">
                                                                              <table style="margin: 0px auto; border-collapse: collapse; width: 100%; border: none;">
                                                                                <tbody>
                                                                                  <tr>
                                                                                    <td style="width: 50px; padding: 0 10px 0 0; vertical-align: top;" valign="top" height="50">
                                                                                      <div style="vertical-align: top; height: 50px; max-height: 50px; width: 100%;"><img style="width: 50px; height: 50px; vertical-align: top;" src="' . $company_image . '" alt="" width="50" height="50" /></div>
                                                                                    </td>
                                                                                    <td style="line-height: normal; vertical-align: top; text-align: left; width: 100%; max-width: 540px; padding: 0;">
                                                                                      <table style="border: none; width: 100%; margin: 0px auto; border-collapse: collapse;">
                                                                                        <tr>
                                                                                          <td style="padding: 0 0 0 0;">
                                                                                            <div style="vertical-align: top; color: #b8b8b8; font-family: arial; font-size: 10px; margin-bottom: 3px; width: 100%;"><span style="color: #999999;">' . $category_name . '</span></div>
                                                                                            <div style="display: block; color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial; margin-bottom: 3px; width: 100%;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="' . $url . '" target="_blank">' . $nodetitle . '</a></div>
                                                                                            <div style="display: block; font-family: arial; font-size: 13px; color: #808080; width: 100%;">' . $nodedata . '</div>
                                                                                          </td>
                                                                                        </tr>
                                                                                        '. $linkedin_recommendations .'
                                                                                        <tr>
                                                                                          <td style="color: #999; font-size:12px; padding: 10px 0 7px 0; font-family: arial;">
                                                                                            <a href="'. $share_linked.'" style="display:inline-block; font-family: arial; color:#2e8cf0; font-size:12px; text-decoration:none;" target="_blank">LinkedIN</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="'. $share_twitter.'" style="font-family: arial; color:#2e8cf0; font-size:12px; display:inline-block; text-decoration:none;" target="_blank">Twitter</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="'. $share_fb.'" style="font-family: arial; color:#2e8cf0; font-size:12px; display:inline-block; text-decoration:none;" target="_blank">Facebook</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="'. $share_google .'" style="font-family: arial;color:#2e8cf0; font-size:12px; display:inline-block; text-decoration:none;" target="_blank">G+</a>
                                                                                          </td>
                                                                                        </tr>
                                                                                      </table>
                                                                                    </td>
                                                                                  </tr>
                                                                                </tbody>
                                                                              </table>
                                                                            </td>
                                                                          </tr>';
                                                              }
                                          $body .= '</tbody></table></td></tr>';
                                          }
                                          else {
                                            $body .= '<tr>
                                              <td style="padding: 10px 20px 20px 20px; width: 100%;">
                                                <table class="both_table" style=" width:100%;margin: 0px auto; border-collapse: collapse; border: none;">
                                                  <tbody><tr class="tr-lvl-5"><td style="width: 100%; border-top: 1px solid #e5e6e9; border-bottom: 1px solid #e5e6e9; padding: 10px;"><div style="font-size:12px; color: #b8b8b8; font-family:arial;">No headlines today.</div></td></tr></tbody></table></td></tr>';
                                          }
                                    /*$body .= '</tbody></table></td></tr>';*/
                                    # Template Body Section For All Content Type End...
                  $body .= '</tbody></table></td></tr>';
                 # Outer Template Body Section Username & Password End...
                   $body .= '<tr>
                  <td>&nbsp;</td>
                </tr>
                <tr>
                  <td style="padding: 0 0 20px 0; text-align: center;" align="center">
                    <p style="text-align: center;"><a style="color: #2e8cf0; font-size: 13px; text-decoration: none; font-family: arial;" href="'. $base_url . '/contact" target="_blank"><span style="color: #2e8cf0; text-align: center; border:none; font-family: arial;"><span style="border:none; text-align: center; font-family: arial, helvetica, sans-serif; font-size: 13px;">Have a question? Contact us!</span></span></a></p>
                    <p style="font-family: arial; text-align: center; border:none; color: #999999; font-size: 13px;">MortgageSpeak</p>
                    <p style="font-family: arial; text-align: center; border:none; color: #999999; font-size: 13px;">1625 W. Balmoral Avenue</p>
                    <p style="font-family: arial; text-align: center; border:none; color: #999999; font-size: 13px;">Suite #2</p>
                    <p style="font-family: arial; text-align: center; border:none; color: #999999; font-size: 13px;">Chicago, IL &nbsp;60640</p>
                  </td>
              </td>
                </tr>';

              $body .= '</tbody></table></td></tr>';      
              # Template Body Section End...

               /*  # Template Sub Header Section Table Closing Start...
              $body .= '</tbody></table></td></tr>';
              # Template Sub Header Section Table Closing End...

            # Template Main Section Table Closing Start...
            $body .= '</tbody></table>';*/
                         
          // Main outer table closing
          $body .= '</tbody></table>';
          # Template Main Section Table Closing  End...

          if ($debug) {
            print("<pre> :: body ::");
            print_r($body);
            print("</pre>");
            exit;
          }
          $node->body['und'][0]['value'] = $body;
          node_save($node);

          drupal_set_message(t("Newsletter content created succesfully!"));
          drupal_goto("admin/content");
          # Template Main Section End...
          #################################################################
          # Create Newsletter Node/Content section end....
          #################################################################
    }
  }
  else {
    $public_newsletter = mortgage_newsletter_public_users();
  }

}

/*
* Function to create Public news letter
*
*/

function mortgage_newsletter_public_users() {
  global $user;
  global $base_url;
  $body = '';
  $abbrtimezone = "CST";
  date_default_timezone_set(timezone_name_from_abbr($abbrtimezone));
  $today              = strtotime("00:00:01");
  $yesterday          = strtotime("-1 day", $today);
  $current            = strtotime("now");

  #################################################################
  # Create Newsletter For Public Users
  #################################################################
    $node = new StdClass();
    $node->type = 'simplenews';
    $node->status = 1;
    $node->uid = 1;
    $node->language = LANGUAGE_NONE;
    $node->title = "Daily Newsletter";
    $node->body['und'][0]['format'] = 'full_html';
    $daily_new_cat = taxonomy_get_term_by_name('Daily Newsletter');
    $daily_new_cat_tid = max(array_keys($daily_new_cat));
    $node->field_simplenews_term[LANGUAGE_NONE][0]['tid'] = $daily_new_cat_tid;

    $body .= '<div style="background-color: #f2f2f2; padding: 10px 0;">
<div style="width: 95%; max-width: 660px; display: block; margin: 0 auto; color: #444444;">
<table class="main-tbl" style="width: 100%; max-width: 660px; border-spacing:0; border-collapse:collapse; border: none; font-family: arial; color: #444444; font-size: 15px; letter-spacing: 0.5px; margin: 0;">
  <tbody>
    <tr class="tr-lvl-1">
      <td style="color: #444444; font-size: 15px; border:1px solid #cccccc; background-color: #FFF; padding: 20px 20px 45px 20px; ">
      <table style="width: 100%; border-spacing:0; border-collapse:collapse; border: none; margin:0; ">
        <tbody>
          <tr class="tr-lvl-2">
            <td style="vertical-align: top; padding: 0 0 20px 0;" valign="top;">
              <a href="'. $base_url .'" style="text-decoration: none; vertical-align: top;" valign="top">
                <img alt="" src="'. $base_url .'/sites/default/files/newdailylogo.png" style="vertical-align: top;" valign="top" />
              </a>
            </td>
          </tr>
          <tr class="tr-lvl-2">
            <td style="padding: 0 0 20px 0; color: #444444; font-size: 15px;">Hi, #userfirstname#.</td>
          </tr>
          <tr class="tr-lvl-2">
            <td style="padding: 0 0 20px 0; color: #444444; font-size: 15px;">MortgageSpeak is <b>updated with new content</b> for #currentdate#.</td>
          </tr>
          <tr class="tr-lvl-2">
            <td style="padding: 0 0 20px 0; width: 100%;"><a href="'. $base_url .'/news" style="width: 100%; display:inline-block; text-align: center; text-decoration: none;"><img alt="" src="'. $base_url .'/sites/all/themes/mortgagespeak/images/btn1.png" style="display:inline-block; width:100%;" /></a></td>
          </tr>
          <tr class="tr-lvl-2">
            <td style="padding: 0 0 15px 0; color: #444444; font-size: 15px; line-height: 22px;">Thank you,<br />
            Greg</td>
          </tr>
          <tr class="tr-lvl-2">
            <td style="padding: 0;">
            <table style="width: 100%; border-spacing:0; border-collapse:collapse; border: none; margin:0;">
              <tbody>
                <tr class="tr-lvl-3">
                  <td style="width:100px; padding: 0;"><span style="display: inline-block; width: 100px; height: 100px; border: 1px solid #2E8CF0; margin: 0 10px 0 0;"><a href="https://www.linkedin.com/in/gregory-janecka-9164842" target="_blank" title="Let\'s connect on LinkedIN."><img alt="" height="100" src="'. $base_url .'/sites/all/themes/mortgagespeak/images/greg.png" style="display: block; height:auto; width:100%;" width="100" /></a></span></td>
                  <td>
                  <table style="width: 100%; border-spacing:0; border-collapse:collapse; border: none; margin:0; ">
                    <tbody>
                      <tr class="tr-lvl-4">
                        <td style="padding: 0 0 5px 0; color: #444444; font-size: 15px; font-weight: bold">Greg Janecka</td>
                      </tr>
                      <tr class="tr-lvl-4">
                        <td style="padding: 0 0 5px 0; color: #444444; font-size: 15px;">Founder and President</td>
                      </tr>
                      <tr class="tr-lvl-4">
                        <td style="padding: 0 0 5px 0; color: #444444; font-size: 15px;"><a href="'. $base_url .'" style="color: #126EDC; text-decoration: none;">MortgageSpeak.com</a></td>
                      </tr>
                      <tr class="tr-lvl-4">
                        <td style="padding: 0 0 5px 0; font-size: 15px;"><span style="color: #88b748;">Sponsor:</span> <a href="'. $base_url .'/effective-promotion-white-paper" style="color: #126EDC; text-decoration: none;">Learn About Effective White Paper Promotion</a></td>
                      </tr>
                    </tbody>
                  </table>
                  </td>
                </tr>
              </tbody>
            </table>
            </td>
          </tr>
        </tbody>
      </table>
      </td>
    </tr>
    <tr class="tr-lvl-1">
      <td style="padding: 50px 0 50px 0;">
       <table style="width: 100%; border-spacing:0; border-collapse:collapse; border: none; margin:0;">
          <tr>
            <td style="width: 65px; padding: 0 5px 0 0; border-right: 1px solid #cccccc;" class="dn-upload-link"><a href="'. $base_url .'/upload" style=" color: #126EDC; text-decoration: none; font-size:15px;"">+ Upload</a></td><td style="padding: 0 0 0 7px;"><a href="'. $base_url .'/contact" style="color: #126EDC; text-decoration: none; font-size:15px;">Contact Us</a></td>
          </tr>
       </table>
      </td>
    </tr>
  </tbody>
</table>
</div>
</div>
';

    $node->body['und'][0]['value'] = $body;
    node_save($node);
    drupal_set_message(t("Public Newsletter content created succesfully!"));
    drupal_goto("admin/content");
}


function googleGenerateShortURL($longurl) {
 //result object to be returned at the end of the function
    $result = array('status' => '0', 'short-url' => '', 'long-url' => '', 'message' => 'Failed to shorten URL.');

    if (!empty($longurl)) {
  foreach($longurl as $key=>$val){

        //build up the options array to be fed into the stream_context object
        $opts = array('http' =>
            array(
                'method' => 'POST',
                'header' => "Content-type: application/json",
                'content' => json_encode(array('longUrl' => $val))
            )
        );

        //attempt to hit the Google API url using a file_get_contents call using our crafted stream context
        try {
            //create stream context using our special options
            $context = stream_context_create($opts);
            $queryreturn = file_get_contents("https://www.googleapis.com/urlshortener/v1/url?key=AIzaSyCPseeK7nca6HTuidF6UeZZjDvcwBEunbM", false, $context);
            //decode the returned JSON object
            $jsondata = json_decode($queryreturn, true);
  
            if ((key_exists('id', $jsondata)) && (strlen($jsondata['id']) > 0)) {
                $result[$key] = array('status' => '1', 'short-url' => $jsondata['id'], 'long-url' => $jsondata['longUrl'], 'message' => 'Succesfully generated short URL.');
                $shorturl[$key] = $jsondata['id'];
            }
        } catch (Exception $e) {
            $result[$key]['message'] = 'Failed to shorten URL. Unable to connect to Google\'s API service.';
            $result[$key]['exception'] = $e->getMessage();
          }
      } 
    }else {
        $result[$key]['message'] = 'Failed to shorten URL. No long URL provided.';
    }

   return $shorturl;
}