<?php

/**
 * @file
 * SimpleAds Campaigns module.
 */

module_load_include('inc', 'simpleads_campaigns', 'includes/helper');

/**
 * Implements hook_permission().
 */
function simpleads_campaigns_permission() {

  return array(
    'access advertisement campaings' => array(
      'title' => t('Access advertisement campaings'),
    ),
  );

}

/**
 * Implements hook_node_info().
 */
function simpleads_campaigns_node_info() {

  return array(
    'simpleads_campaigns' => array(
      'title_label' => t('Campaign Title'),
      'name' => t('Advertisement campaign'),
      'base' => 'simpleads_campaigns',
      'description' => t('Use this content type to create advertisement campaigns.'),
    ),
  );

}

/**
 * Implements hook_form().
 */
function simpleads_campaigns_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function simpleads_campaigns_form_simpleads_campaigns_node_form_alter(&$form, &$form_state, $form_id) {

  $form['#attached']['js'][] = drupal_get_path('module', 'simpleads_campaigns') . '/js/node.js';
  $form['#attached']['css'][] = drupal_get_path('module', 'simpleads_campaigns') . '/css/node.css';
 
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function simpleads_campaigns_form_simpleads_node_form_alter(&$form, &$form_state, $form_id) {

  $form['#attached']['js'][] = drupal_get_path('module', 'simpleads_campaigns') . '/js/simpleads_node.js';

  if ( isset($form['field_adcamp_list']) && !user_access('access advertisement campaings') ) {
    hide($form['field_adcamp_list']);
  }
 
}

/**
 * Implements hook_simpleads_campaign_complete().
 */
function simpleads_campaigns_simpleads_campaign_complete($node, $campaign) {

  $variables = array(
    '@title' => $node->title,
    '@nid' => $node->nid,
    '@campaign' => $campaign->title,
    '@campaign-nid' => $campaign->nid,
  );

  watchdog('simpleads_campaigns', '@title (@nid) successfully completed @campaign (@campaign-nid).', $variables, WATCHDOG_INFO);

}
